# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: |
        dotnet publish --configuration Release --os linux -p:PublishSingleFile=true -p:PublishTrimmed=true --output publish
        dotnet publish --configuration Release --os win -p:PublishSingleFile=true -p:PublishTrimmed=true --output publish
        
    - name: Publish artifacts
      uses: softprops/action-gh-release@v2
      if: |
        startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          publish/*
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
