# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
permissions:
  contents: write

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: |
        dotnet publish --configuration Release --os win -p:PublishSingleFile=true -p:PublishTrimmed=true
        zip -rj win64.zip bin/Release/net8.0/win-x64/publish
        dotnet publish --configuration Release --os linux -p:PublishSingleFile=true -p:PublishTrimmed=true
        tar -cf linux64.tar -C bin/Release/net8.0/linux-x64/publish .
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: |
          win64.zip
          linux64.tar
          
    - name: Publish artifacts
      uses: softprops/action-gh-release@v2
      if: |
        startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          win64.zip
          linux64.tar
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
